apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flask-app-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: flask-app
  policyTypes:
  - Ingress
  ingress:
  # Règle 1 : Autoriser Prometheus (pour les graphs)
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - protocol: TCP
      port: 5000
  # Règle 2 : Autoriser le trafic extérieur (ton navigateur)
  - from: [] # Vide signifie "Autoriser tout le monde" (Ingress)
    ports:
    - protocol: TCP
      port: 5000
