apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: flask-app-policy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: flask-app
  policyTypes:
  - Ingress
  ingress:
  # Règle 1 : Autoriser Prometheus (pour les graphs)
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: monitoring
    ports:
    - protocol: TCP
      port: 5000
  # Règle 2 : Autoriser le trafic extérieur (ton navigateur)
  - from:
    - ipBlock:
        cidr: 192.168.1.0/24 
    # 2. Autorise les IPs internes de K3s (pour la VM elle-même)
    - ipBlock:
        cidr: 10.42.0.0/16 # Réseau des Pods K3s
    - ipBlock:
        cidr: 127.0.0.1/32
    ports:
    - protocol: TCP
      port: 5000
